all:
  children:
    ubuntu:
      hosts:
        localhost:
        172.31.7.144:
    redhat:
      hosts:
        172.31.31.169:
    app_server:
      hosts:
        172.31.7.144:
        172.31.31.169:
# all r having keys but no values


all:
  hosts:
        localhost:
        172.31.7.144:
        172.31.31.169:
