# mysql database user name and his password
---
apiVersion: v1
kind: Secret
metadata:
  name: db-user
data:
  username: dGVzdHVzZXI=     # echo -n 'testuser' | base64
  password: dGVzdHVzZXJAMTIz  #  echo -n 'testuser@123' | base64