---
- name: installing odoo
  hosts: all
  become: yes 
  vars:
    - include_vars: vars.yml
  tasks:
    - include_tasks: installing_tools.yml
    - include_tasks: odoo_user.yml
    - include_tasks: wkhtml.yml
    - include_tasks: git.yml
    - include_tasks: venv.yml
    - include_tasks: odoo_setup.yml
    - include_tasks: enabling_odoo_service.yml
  handlers:
    - include_handlers: handlers.yml