---
- name: Install Java
  become: yes
  hosts: appserver
  tasks:
    - name: install openjdk 11
      package:
        name: "{{ java_package }}"
        state: present
#no update chache here
#package is a generic package module used here for os installations to make easy except windows
