---
- name: install java 11
  become: yes
  hosts: all
  tasks:
    - name: installing java
      ansible.builtin.package:
        name: "{{ java_package }}"
        state: present
        update_cache: yes
    


    